# Generated by Django 4.2.2 on 2023-08-22 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "None"),
                            (1, "Card"),
                            (2, "Installment"),
                            (3, "Apple Pay"),
                            (4, "Google Pay"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "bank_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "UFC"),
                            (2, "Bank Of Georgia"),
                            (3, "TBC"),
                            (4, "Credo"),
                            (5, "Space"),
                            (6, "Georgian Card"),
                        ],
                        default=3,
                        verbose_name="Bank",
                    ),
                ),
                ("min_amount", models.FloatField(default=0, verbose_name="Min Amount")),
                ("max_amount", models.FloatField(default=0, verbose_name="Max Amount")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "unique_together": {("payment_type", "bank_type")},
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("number", models.CharField(max_length=16)),
                ("rec_id", models.CharField(default="", max_length=41)),
                ("expiry_date", models.CharField(default="0000", max_length=5)),
                ("record_date", models.DateTimeField(auto_now_add=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            (1, "Visa"),
                            (2, "Mastercard"),
                            (3, "American Express"),
                            (4, "Unknown"),
                        ],
                        default=1,
                        max_length=255,
                    ),
                ),
                (
                    "bank_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "UFC"),
                            (2, "Bank Of Georgia"),
                            (3, "TBC"),
                            (4, "Credo"),
                            (5, "Space"),
                            (6, "Georgian Card"),
                        ],
                        default=1,
                        verbose_name="Bank",
                    ),
                ),
                (
                    "card_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
